### PR TITLE
OpenHAB integration

### PR DESCRIPTION
**Pull request by Moxified**
Basic OpenHAB integration setup.

### CODE REVIEW

**Comment by SwiCago** [comment]
Thanks @Moxified , did you use latest library code for your demo ino files?

**Comment by Moxified** [comment]
@SwiCago, Unfortunately I'm sure I did not.  I pulled down the library a year ago and started modifying the mqtt example for my purposes.  I don't recall how much was for things like millis rollover and wifi reconnect handling and how much was for OH. 

iirc, the library mqtt example code doesn't handle wifi loss well and also doesn't handle milli rollover properly.  I could be wrong.  I feel like when I would update AP firmware and it would bounce them from AP to AP, sometimes they would fail to reconnect and have to be powered off physically.  That was a year ago and I have done probably 10 other iot projects since then.  I just know that the way I have my code in that example is very resilient to millis rollover as well as mqtt and wifi disconnects and I use it across all of my esp projects.

Please excuse my amateur level.  I'm not super familiar with source control.  I don't know what the best method would be to keep the custom .ino compatible with the official mqtt example as I don't suspect I will be reliable to updating it.

I actually have substantially more added in to my version that offers ntp based uptime reporting for heartbeat monitoring from OH and more.  I did strip that out as few would care about that besides me.

I can try to find some time to start over with the example and find exactly what bits are required for OH and we could possibly discuss adding them as a function or something to the library example that can be turned on or off with a variable perhaps?  This may be a few weeks as summer is busy for me.

**Comment by SwiCago** [comment]
@Moxified no worries. I was only asking, in case some dumb ass opens an issue. That way I can refer them to you ;)
I guess I have been lucky, my setup consists of 6 HPs, 2 remote temp sensors amd 1 six zone hydronic controller. All have been running for well over a year now, with I believe only 2 power outages total. But then again, I made my own controller software. No openhab or homeassistant for me

**Comment by Moxified** [comment]
LOL!  No doubt and feel free!  Mine have been pretty reliable.  I'll try to go back through it anyway when I get time.  It isn't the power outages, they reconnect after that, it's when AP's go down but the esp's stay up, they would get stuck and just stop trying.  I do have to open an issue related to my HP's turning off (or on if off) when changing set temp rapidly.  I need to do some debugging first cause all I have right now is that it has happened several times now and always when stepping through temp.  But that's for a different place.

**Pull request merged**
