### PR TITLE
Convert to char* to save memory

### PR DESCRIPTION
**Pull request by schotime**

### CODE REVIEW

**Comment by schotime** [comment]
#57

**Comment by kmdm** [comment]
`constexpr` not work?

**Comment by schotime** [comment]
It did not.

**Comment by SwiCago** [comment]
I will review as soon as my hoipuse's drywall os done. That should be in the next wek and a half. Please be patient. Thanks

**Comment by schotime** [comment]
Whered this get to?

**Comment by rtwfroody** [comment]
This is a step in the right direction, but why not go all the way and get rid of the strings altogether? I'm thinking:
```
struct heatpumpSettings {
  enum { POWER_OFF, POWER_ON } power;
  enum { MODE_HEAT, MODE_DRY, MODE_COOL, MODE_FAN, MODE_AUTO } mode;
  float temperature;
  enum { FAN_AUTO, FAN_QUIET, FAN_1, FAN_2, FAN_3, FAN_4 } fan;
  enum { VANE_AUTO, VANE_1, VANE_2, VANE_3, VANE_4, VANE_5, VANE_SWING} vane; //vertical vane, up/down
  enum { WIDE_VANE_FAR_LEFT, WIDE_VANE_LEFT, WIDE_VANE_CENTER, WIDE_VANE_RIGHT, WIDE_VANE_STRONG_RIGHT, WIDE_VANE_LEFT_RIGHT, WIDE_VANE_SWING} wideVane; //horizontal vane, left/right
  bool iSee;   //iSee sensor, at the moment can only detect it, not set it
};
```

That's a lot more compact than using strings, and the code will be faster also. In addition now we could get rid of the maps, which bloat code size.
On top of that it will help catch some program bugs early. Eg. currently my code might read:
```
settings.power = "on";
```
and that would silently end up with the power actually being off. With the enums:
```
settings.power = power_on;
```
would be a compile time error.

If it's necessary there could be some helper functions which return or accept string representations of these values, but if we structure it right these would only add to the code size if they are actually called.

**Comment by SwiCago** [comment]
@kayno @lekobob could either of you test lekebobs pull and confirm it works. I have been really swamped and have not played with the code in a long while. For me current code works fine, but improvements are always welcome

**Comment by SwiCago** [comment]
Too old and too many conflicts

**Pull request closed without merging**
