### PR TITLE
manage 2400 and 9600 bitrate (MSZ-GC only works at 9600 bps)

### PR DESCRIPTION
**Pull request by PiR43**

### CODE REVIEW

**Comment by PiR43** [comment]
Hi, 
I have let the connect method with only one parameter (it call the second version with second parameter at true):
```
bool HeatPump::connect(HardwareSerial *serial) {
 	connect(serial,true);
 }
```
So no problem for example or upgrade.
For the moment I use the example with no change in the example only my change in library and all works fine. I have also put 2400 by default like majority of devices seems ok with it.

**Comment by llemtt** [comment]
Library is C++ so I don't see problems **adding** methods

bool HeatPump::connect(HardwareSerial *serial, int bitrate)

bool HeatPump::connect(HardwareSerial *serial, int bitrate, boolean retry)

Nothing will be broken in existing code.

**Comment by SwiCago** [comment]
@llemtt  adding methods is fine. It is when changing a method and not adding a new one, that all existing code breaks. I would hate for a arduino nn00b to download this library and then the example don't compile, because of missing param, because the method was changed and not made backwards compatible

**Comment by SwiCago** [comment]
I will review the changes requested, when I have time and either merge or make changes. Thanks for the contribution. It is always helpful to make it better.

**Comment by SwiCago** [comment]
No my other question is, will this ruin the char* commit from yesterday. This pull does not include it. Git says no conflict, but will it merge right or over write yesterdays commit with stale data?

**Comment by PiR43** [comment]
I have merge the char * commit in this pull request, I hope it will help.

**Comment by SwiCago** [comment]
Looks good now. Thanks

**Pull request merged**
