### PR TITLE
External update

### PR DESCRIPTION
**Pull request by schotime**

### CODE REVIEW

**Comment by SwiCago** [comment]
Not sure i agree with this update other than the float. I dont think an external source should be allowed to change the wanted settings of sketch. External source already is saved in current settings and reported back, so it should not over write wanted settings. 
Ex: say i set mode to cool and 20C in schedule, then someone with ir changes mode to fan. Later schedule only updates temp to 22C. Well in this case it will not cool anymore as IR changed mode to fan. 
Current settings is what heat pump currently reports, wanted are for when it does a update. 
Maybe the conflict is when auto update is enabled? Maybe this is something that would have to be combined if auto update is enabled, as auto would change the hp back to wanted after every ir change, is that the case @schotime ..if so, please combine with autoupdate

In my case, i am not using autoupdate, so IR never gets over written until my sketch sends a update.
What do you think @kayno ?

**Comment by schotime** [comment]
It is indeed when autoUpdate is on. Have updated to include that.

**Comment by SwiCago** [comment]
@schotime looks good merging

**Comment by kayno** [comment]
@SwiCago @schotime trying to get my head around this change. If the issue is that when autoupdate is on, IR (infra red remote control) changes are overwritten by wantedSettings every time, wouldn't it be best just to fix this as part of switching on autoUpdate, rather than having to do call another function?

It just doesn't seem intuitive. When i first saw this merge, I assumed (from the title) it was related to sending external temperature updates...

**Comment by SwiCago** [comment]
@kayno, i thought that too...that it was about external temp lol....
Yes it seems counter intuitive. If you dont want IR to be over written, turn autoupdate off and only update from sketch. May want to revert that part, but thought I'd wait for your opinion. I let it merge as the rest of us are not using auto update.

**Comment by kayno** [comment]
Might be good to have your use case for this, @schotime, so we can better understand.

In a way I think we have over-complicated the library when it comes to autoUpdate. In hindsight, perhaps we should have gone one way or the other, rather than having it optional. I can see pros and cons to both having autoupdate and not having it. 

We could, for instance, strip the library right back, and just have a small set of public functions - `connect()`, `sync()`, `getSettings()`, `setSettings()`. When `setSettings()` is called it sends the change to the heatpump. This is the approach @jarrod180 took, and I really like the simplicity.

My preference is to have a little more control though. I like having the individual setters and getters (e.g. `setPowerSetting()`, `setFanSpeed()`, etc), and things like the callbacks. Again in hindsight, having these individual setters probably dictates that we shouldn't have autoUpdate, as ideally you let the end user of the library call any combo of setters, then do an `update()`.  

We could also go extreme, and have the library mimic everything that the IR remotes and wall controllers do - for example setting timers. I agree with @SwiCago though on this one - we don't want to start doing what the users of the library (e.g. home automation tools like home-assistant.io and openhab.org) should be taking care of.

IMO, I think we should consider scrapping autoUpdate. I am happy for others to persuade me though on why it should be kept, but I think it's just over complicating things. I think I was the one who originally suggested implementing it, but my original idea was to just call `update()` from each of the setting setters, and make `update()` private. I'm no longer even comfortable with that idea though! Given @schotime is using autoUpdate, I would be interested in his use case in case I've missed something in my thought process.

**Comment by schotime** [comment]
I like the idea of having it a simple as possible as well as long as the "things" that a sketch author must assume to be correct aren't great.

I want to be able to override my air con with the IR. Whether that be because I don't have my phone on me, or the box with hass has gone down or whatever. That's a requirement I have.

The reason I went with the autoUpdate was because I didn't want to have to manage the setting of the settings manually (if that makes sense). eg. before I would have to do this.

```
void loop() {
  if(sendUpdate) {
    hp.setSettings(newSettings);
    hp.update();
    sendUpdate = false;
  } 
  else {
    hp.sync();    
  }

  sleep(1000);
}
```

Making sure that I set the `sendUpdate` variable in my receive method that gets called by mysensors when it receives data from hass.

With autoUpdate that syncing is done for me. eg. If there are updates then update. if there are done, then don't.

The loop becomes the below. Which as a consumer of a library is very easy to consume.
```
void loop() {
  hp.sync();
  sleep(1000);
}
```

Anyways...i'm still having massive problems with the !connect() wait loop, so I just have to call connect() and not look at the return because it doesn't return straight away. Its kind of like when you call update(), I don't get the confirmation straight away either. Usually it takes 2 or 3 goes.

So I hope this gives you more insight to why I'm using it, but I'd be happy to have it a lot simpler as long as its clear that you need to manage the update syncing yourself as above.

**Comment by SwiCago** [comment]
@kayno, @schotime, when i first started this library it was bare bones simple. I liked individual getter and setters as from a oop point of view it makes sense. It makes it easy for people who come from java background to understand. Now for auto update, i could care less..however i saw no harm in including it to make it more versatile. No harm in giving users options that make coding easier and also no harm it making it full manual mode for those that like full control. A good library is both easy to use and gives versatility. Timers, who needs them. I don't, but you discovered it and it gives people who may need it that option. No harm in it being there. 
Now to what i believe we can all agree on, this library needs some house cleaning. We have discovered so many neat features and kept adding on top. I say as soon as error codes is confirmed or the operational codes are confirmed and the remote temp sense is added, we do clean up. Re-evaluate the code base and clean it up, knowing what we know now.

**Comment by kayno** [comment]
Agree with you, @SwiCago.

@schotime @SwiCago Would there ever be a scenario where you'd call `enableAutoUpdate()` and not `enableExternalUpdate()`?

**Comment by schotime** [comment]
@kayno where you didn't want to allow IR updates.

**Comment by kayno** [comment]
@schotime my first thought to that was "hide the remote control!" But then I guess you could have a fixed controller on the wall that someone might keep adjusting, and you want to override. Maybe another case for handling in whatever uses the Library, e.g. home automation software...

Could be a useful feature though. I think it would be more intuitive to expose this feature as `enforceSettings()` or `overrideControllers()`. Default should be that the library is just another controller. Also it should be untied from autoUpdate (if it is tied together) - I may want to control when `update()` is called and not use autoUpdate, and also enforce the settings that the library sets (I just said "enforce the settings", so I think the function should be called `enforceSettings()` :))

**Comment by SwiCago** [comment]
@kayno, update could be built into sync.
If enforce is on, then any IR command just get over written. If enforce is off, the IR becomes part of wanted.
This would get rid off a few redundant items. Default is enforce off, so that IR comes back to wanted. But when that occurs any automation has to be made aware(upto user), so that if only a temp setting is changed, but mode was changed from cool to fan by IR, then it must update mode as well..otherwise it stays on the last mode from IR and does not cool... honestly automation should probably always at minimum send power,mode and temp...that way when it is time to change it is garuanteed to happen

**Pull request merged**
